### ISSUE TITLE
Show fields by Entry Type along with fieldgroup

### ISSUE THREAD

**Issue by keithmancuso** [focuslabllc/craft-field-cheat-sheet#20]
Listing fields by field group is helpful but would be much more useful if it also let you see all the fields sorted and grouped by section and entry type.  

Hoping something like this is in the works.

**Comment by erikreagan** [comment]
Thanks @keithmancuso. I like that. Let me look into how accessible that data is within a normal Craft template and see if there's a way to build something like this.

For my use of this so far, I usually know what field(s) I'm looking for so I just use the field search box to find it super fast. I can see how grouping by section may be helpful though.

**Comment by erikreagan** [comment]
@keithmancuso after reviewing this in detail, I'm afraid it won't be something we can work into the Cheat Sheet. Too much overhead and too complicated to traverse data through twig.

I do have plans and idea for a Plugin version of the Cheat Sheet, so I'll mark this as a feature for that version. It will be much more accessible when I'm building and querying with PHP rather than Twig.

Thanks!
